#!/bin/bash
#
# Remotely run ExtendScript commands
#
# Direct command:
#
#   doe <target> "some extendscript code"
#
# Read from stdin:
#
#   doe <target> 
#
# e.g.
#
#   doe indesign "app.quit();"
#

if [ "$1" = "" ]; then
    echo "Direct command:"
    echo "  `basename \"$0\"` target \"command\""
    echo "Read from stdin:"
    echo "  `basename \"$0\"` target"
    exit
fi

export RRE_REMOTE_URL="$1"

if [ "$2" = "" ]; then
    cat > /tmp/doe_script_file.jsx
    export RRE_SCRIPT_FILE="/tmp/doe_script_file.jsx"
    Tightener -N scriptrunner -f "${TIGHTENER_SCRIPTS}rre_REPL_file.tql"
else
    export RRE_ONE_LINE="$2"
    Tightener -N scriptrunner -f "${TIGHTENER_SCRIPTS}rre_REPL_1line.tql"
fi


