@ECHO off

CALL "%TIGHTENER_SCRIPTS%idSetEnv.bat"

IF "%INDESIGN_TIGHTENER_IS_SERVER%" == "1" (
    "%INDESIGN_APP_ROOT%%INDESIGN_APP_FILE%" -console
) ELSE (
    "%INDESIGN_APP_ROOT%%INDESIGN_APP_FILE%"
)

