@ECHO off

CALL "%TIGHTENER_SCRIPTS%idSetEnv.bat"

IF "%INDESIGN_TIGHTENER_IS_SERVER%" == "1" (
    IF EXIST "%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%TightenerServer.pln" (
        SET PLUGIN=%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%TightenerServer.pln
    )
    ELSE (
        SET PLUGIN=%INDESIGN_APP_PLUGIN_FOLDER%TightenerServer.pln
    )
    IF EXIST "%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%APIDToolAssistant%INDESIGN_TIGHTENER_CS_VERSION%%INDESIGN_TIGHTENER_SDK_VERSION%.pln" (
        SET APID_PLUG_IN_FILE=%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%APIDToolAssistant%INDESIGN_TIGHTENER_CS_VERSION%%INDESIGN_TIGHTENER_SDK_VERSION%.pln
    )
    ELSE (
        SET APID_PLUG_IN_FILE=%INDESIGN_APP_PLUGIN_FOLDER%APIDToolAssistant%INDESIGN_TIGHTENER_CS_VERSION%%INDESIGN_TIGHTENER_SDK_VERSION%.pln
    )
) ELSE (
    IF EXIST "%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%Tightener.pln" (
        SET PLUGIN=%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%Tightener.pln
    )
    ELSE (
        SET PLUGIN=%INDESIGN_APP_PLUGIN_FOLDER%Tightener.pln
    )
    IF EXIST "%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%APIDToolAssistant%INDESIGN_TIGHTENER_CS_VERSION%%INDESIGN_TIGHTENER_SDK_VERSION%.pln" (
        SET APID_PLUG_IN_FILE=%INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%APIDToolAssistant%INDESIGN_TIGHTENER_CS_VERSION%%INDESIGN_TIGHTENER_SDK_VERSION%.pln
    )
    ELSE (
        SET APID_PLUG_IN_FILE=%INDESIGN_APP_PLUGIN_FOLDER%APIDToolAssistant%INDESIGN_TIGHTENER_CS_VERSION%%INDESIGN_TIGHTENER_SDK_VERSION%.pln
    )
)

IF EXIST "%PLUGIN%" (
    SET TIGHTENER_INDESIGN_CHANNEL=InDesignTightener
) ELSE IF EXIST "%APID_PLUG_IN_FILE%" (
    SET TIGHTENER_INDESIGN_CHANNEL=APID
)
ELSE (
    ECHO.Aborting.
    ECHO.No Tightener Plug-in installed in
    ECHO.   %INDESIGN_APP_ROROHIKO_PLUGIN_FOLDER%
    ECHO.You can try using idPluginInstall to install it.
    GOTO DONE
)

IF "%INDESIGN_TIGHTENER_IS_SERVER%" == "1" (
    IF "%1" == "" (
        "%INDESIGN_APP_ROOT%%INDESIGN_APP_FILE%" -console
    ) ELSE (
        "%INDESIGN_APP_ROOT%%INDESIGN_APP_FILE%" -console -configuration "%1"
    )
) ELSE (
    idPoke
)

:DONE